name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          platforms;android-33
          ndk;25.1.8937393
          cmake;3.18.1
        cache: true
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug
      env:
        TERM: dumb