name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'
    - name: Install Android SDKs
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          platforms;android-33
          ndk;25.1.8937393
          cmake;3.18.1
        cache: true
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      env:
        TERM: dumb
    - name: Android Lint
      run: ./gradlew lint
      env:
        TERM: dumb
    - name: Upload lint report
      uses: actions/upload-artifact@v3
      with:
        name: lint_report.html
        path: app/build/reports/lint-results-debug.html
